### ISSUE TITLE
Error when trying to submit

### ISSUE THREAD

**Issue by Giagnus64** [learn-co-curriculum/html-fundamentals-html-images-lab#1]
After passing tests and entering "learn submit" into the console, the console spits back out this error : 
```bash
Traceback (most recent call last):
        8: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        7: from /usr/local/rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
        6: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-submit:23:in `<main>'
        5: from /usr/local/rvm/gems/ruby-2.6.1/bin/learn-submit:23:in `load'
        4: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-submit-1.3.1/bin/learn-submit:15:in `<top (required)>'
        3: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-submit-1.3.1/lib/learn_submit/submission.rb:9:in `create'
        2: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-submit-1.3.1/lib/learn_submit/submission.rb:29:in `create'
        1: from /usr/local/rvm/gems/ruby-2.6.1/gems/learn-submit-1.3.1/lib/learn_submit/submission.rb:148:in `submit!'
/usr/local/rvm/gems/ruby-2.6.1/gems/learn-submit-1.3.1/lib/learn_submit/submission.rb:152:in `submit!': undefined method `match' for nil:NilClass (NoMethodEr
ror)
```
I've been able to submit other labs with no issues.

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub][issues] should be reserved for problems with the
curriculum itself (doesn't work, throws a Ruby error, etc.)

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try
to discern a proper path to resolution.

[issues]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
